# Generated by Django 3.2.4 on 2021-06-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210610_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='sales_prise',
            new_name='sales_price',
        ),
    ]
