# Generated by Django 3.2.4 on 2021-06-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_advertisement_sales_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created']},
        ),
    ]
